version: '3.3'

services:
  jenkins:
    build:
      context: ./
    ports: 
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./config/:/var/jenkins_conf/
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_conf/
volumes:
  jenkins_home:
